name: flutter_contact
version: 0.6.5+1
homepage: https://github.com/SunnyApp/flutter_contact
description: A Flutter plugin to retrieve, create and save contacts and contact-related events on Android and iOS devices.
maintainer: Eric Martineau
environment: 
  sdk: '>=2.6.0 <3.0.0'
  flutter: ^1.10.0
dependencies: 
  collection: ^1.14.11
  equatable: ^1.2.5
  intl: ^0.16.1
  logging: ^0.11.4
  logging_config: ^0.4.7
  quiver: ^2.1.3
  sunny_dart: ^0.5.8+5
  uuid: ^2.2.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: co.sunnyapp.flutter_contact
        pluginClass: FlutterContactPlugin
      ios: 
        pluginClass: FlutterContactPlugin
