name: flutter_contact
description: A Flutter plugin to retrieve, create and save contacts and contact-related events on Android and iOS devices.
version: 0.5.1+1
homepage: https://github.com/SunnyApp/flutter_contact
maintainer: Eric Martineau

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.4

  logging: ^0.11.4
  logging_config: ^0.4.7

  # Simple equality cases
  equatable: ^1.0.2

  # Collection equality
  collection: ^1.14.11

  # Utilities (== hashCode generation)
  quiver: ^2.0.5

  # Static code analysis
  pedantic: ^1.8.0+1

  # Low-level utilities
  sunny_dart: ^0.5.2

  # Formatting/parsing of dates
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: co.sunnyapp.flutter_contact
    pluginClass: FlutterContactPlugin

