name: flutter_contact
version: 0.8.1-nullsafety.0
homepage: https://github.com/SunnyApp/flutter_contact
description: A Flutter plugin to retrieve, create and save contacts and contact-related events on Android and iOS devices.
maintainer: Eric Martineau
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^1.10.0
dependencies: 
  collection: ^1.15.0
  dartxx: ^0.4.4
  equatable: ^2.0.0
  flexidate: ^0.4.4
  intl: ^0.17.0
  logging: ^1.0.0
  logging_config: ^0.6.7
  quiver: ^3.0.0
  uuid: ^3.0.1
  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.11.0
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: co.sunnyapp.flutter_contact
        pluginClass: FlutterContactPlugin
      ios: 
        pluginClass: FlutterContactPlugin
